name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build CPP Teaching
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Make the Entire Apps
      run: make
    
    - name: Clean
      run: make clean
