name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Buat CPP Teaching
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Buat semua aplikasi
      run: make
